name: Build GOTY
on:
  push:
    branches:
      - archipelago

jobs:
  build:
    runs-on: windows-latest
    strategy: 
      fail-fast: false
      matrix:
        configuration: [ReleaseGOTY, DebugGOTY]
        platform: [x64, Win32]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with: 
          submodules: recursive
      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: msbuild
        run: |
          msbuild /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} PlantsVsZombies.sln
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: PlantsVsZombies-GOTY-${{ matrix.configuration }}-${{ matrix.platform }}
          path: |
            build/${{ matrix.configuration }}_${{ matrix.platform }}/bin